import { Router } from 'express';
import authRoutes from './auth.routes';
import productRoutes from './product.routes';
import ingredientRoutes from './ingredient.routes';
import publicRoutes from './public.routes';
import devRoutes from './dev.routes';
import categoryRoutes from './category.routes';
import tableRoutes from './table.routes';
import orderRoutes from './order.routes';
import saleRoutes from './sale.routes';
import cashierRoutes from './cashier.routes';
import dashboardRoutes from './dashboard.routes';
import userRoutes from './user.routes';
import companyRoutes from './company.routes';
import stockRoutes from './stock.routes';
import reportsRoutes from './reports.routes';
import settingsRoutes from './settings.routes';
import paymentRoutes from './payment.routes';
import courierRoutes from './courier.routes';
import customerRoutes from './customer.routes';
import complementRoutes from './complement.routes';

const router = Router();

router.use('/public', publicRoutes);
router.use('/auth', authRoutes);
router.use('/products', productRoutes);
router.use('/ingredients', ingredientRoutes);
router.use('/dev', devRoutes);
router.use('/categories', categoryRoutes);
router.use('/tables', tableRoutes);
router.use('/orders', orderRoutes);
router.use('/sales', saleRoutes);
router.use('/cashier', cashierRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/users', userRoutes);
router.use('/companies', companyRoutes);
router.use('/stock', stockRoutes);
router.use('/reports', reportsRoutes);
router.use('/settings', settingsRoutes);
router.use('/payments', paymentRoutes);
router.use('/couriers', courierRoutes);
router.use('/customers', customerRoutes);
router.use('/complements', complementRoutes);

export default router;
